version: "3.9"
services:
  view:
    build: ./image-pipeline
    environment:
      - DISPLAY=host.docker.internal:0
    command:
      [
        "ros2",
        "run",
        "image_view",
        "image_view",
        "--ros-args",
        "--remap",
        "/image:=${TELLO_IMAGE_RAW}"
      ]
  replay:
    build: ./notebook
    command:
      [
        "ros2",
        "run",
        "py_pubsub",
        "talker",
        "--ros-args",
        "--remap",
        "/image:=${TELLO_IMAGE_RAW}"
      ]
    tty: true
    volumes:
      - "./data:/opt/ros/overlay_ws/data"
  inference:
    build: ./notebook
    volumes:
      - "./notebook:/opt/ros/overlay_ws/src"
    tty: true
  tello:
    build: ./tello
