version: "3.9"
services:
  view1:
    build: ./image-pipeline
    environment:
      - DISPLAY=host.docker.internal:0
    command:
      [
        "ros2",
        "run",
        "image_view",
        "image_view",
        "--ros-args",
        "--remap",
        "/image:=${TELLO_IMAGE_RAW}",
        "-p",
        "autosize:=true"
      ]
  view2:
    build: ./image-pipeline
    environment:
      - DISPLAY=host.docker.internal:0
    command:
      [
        "ros2",
        "run",
        "image_view",
        "image_view",
        "--ros-args",
        "--remap",
        "/image:=/bounding_box",
        "-p",
        "autosize:=true"
      ]
  replay:
    build: ./notebook
    command:
      [
        "ros2",
        "run",
        "py_pubsub",
        "talker",
        "--ros-args",
        "--remap",
        "/image:=${TELLO_IMAGE_RAW}"
      ]
    volumes:
      - "./notebook:/opt/ros/overlay_ws/src"
      - "./data:/opt/ros/overlay_ws/data"
  inference:
    build: ./notebook
    volumes:
      - "./notebook:/opt/ros/overlay_ws/src"
      - "./data:/opt/ros/overlay_ws/data"
    command:
      [
        "ros2",
        "run",
        "py_pubsub",
        "listener",
        "--ros-args",
        "--remap",
        "/image:=${TELLO_IMAGE_RAW}"
      ]
  tello:
    build: ./tello
  console:
    build: ./rqt
    environment:
      - DISPLAY=host.docker.internal:0
    command: [ "ros2", "run", "rqt_console", "rqt_console" ]
