version: "3.9"
services:
  view1:
    build: ./notebook
    environment:
      - DISPLAY=host.docker.internal:0
    command:
      [
        "ros2",
        "run",
        "image_view",
        "image_view",
        "--ros-args",
        "--remap",
        "/image:=${TELLO_IMAGE_RAW}",
        "-p",
        "autosize:=true"
      ]
  view2:
    build: ./notebook
    environment:
      - DISPLAY=host.docker.internal:0
    command:
      [
        "ros2",
        "run",
        "image_view",
        "image_view",
        "--ros-args",
        "--remap",
        "/image:=${BOUNDING_BOX_IMAGE_RAW}",
        "-p",
        "autosize:=true"
      ]
  replay:
    build: ./notebook
    command:
      [
        "ros2",
        "run",
        "py_pubsub",
        "talker",
        "--ros-args",
        "--remap",
        "/image:=${TELLO_IMAGE_RAW}"
      ]
    volumes:
      - "./notebook:/opt/ros/overlay_ws/src"
      - "./data:/opt/ros/overlay_ws/data"
  console:
    build: ./notebook
    environment:
      - DISPLAY=host.docker.internal:0
    command: [ "ros2", "run", "rqt_console", "rqt_console" ]
  inference:
    build: ./notebook
    volumes:
      - "./notebook:/opt/ros/overlay_ws/src"
      - "./data:/opt/ros/overlay_ws/data"
      - "~/.cache:/root/.cache"
    command:
      [
        "ros2",
        "run",
        "py_pubsub",
        "listener",
        "--ros-args",
        "--remap",
        "/image:=${TELLO_IMAGE_RAW}"
      ]
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [ gpu ]
  tello:
    build: ./tello
