version: "3.9"
services:
  tello:
    build: ./tello
    environment:
      - DISPLAY=host.docker.internal:0
    network_mode: "host"
  buffer:
    build: ./notebook
    environment:
      - DISPLAY=host.docker.internal:0
    command:
      [
        "ros2",
        "run",
        "tello_gate",
        "buffer",
        "--ros-args",
        "--remap",
        "/image:=${TELLO_IMAGE_RAW}"
      ]
    volumes:
      - "./notebook:/opt/ros/overlay_ws/src"
  replay:
    build: ./notebook
    environment:
      - DISPLAY=host.docker.internal:0
    command:
      [
        "ros2",
        "run",
        "tello_gate",
        "replay",
        "--ros-args",
        "--remap",
        "/image:=${TELLO_IMAGE_RAW}"
      ]
    volumes:
      - "./notebook:/opt/ros/overlay_ws/src"
      - "./data:/opt/ros/overlay_ws/data"
  inference:
    build: ./notebook
    environment:
      - DISPLAY=host.docker.internal:0
    command:
      [
        "ros2",
        "run",
        "tello_gate",
        "inference",
        "--ros-args",
        "--remap",
        "/image:=${TELLO_IMAGE_RAW}"
      ]
    volumes:
      - "./notebook:/opt/ros/overlay_ws/src"
      - "./data:/opt/ros/overlay_ws/data"
      - "~/.cache:/root/.cache"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [ gpu ]
  console:
    build: ./notebook
    environment:
      - DISPLAY=host.docker.internal:0
    command: [ "ros2", "run", "rqt_console", "rqt_console" ]
